#!/bin/bash
encrypt=''
filename='pkuweb'

read -p "Please Input the studentID:" studentID
read -s -p "Please Input the password:" password
echo ""
read -p "Please Input the args to domestic(default: free):" domestic
read -p "Please Input the args to global(default: glb):" global
read -p "Please Input the args to disconnect(default: dis):" disconnect
read -p "Please Input the args to disconnectall(default: disall):" disconnectall
read -p "Whether encrypt the shell script(Y/n):" encrypt

if [[ $encrypt = 'n'  ||  $encrypt = 'N' ]]
then
    encrypt=0
    echo "Encrypt: NO"
else
    encrypt=1
    echo "Encrypt: YES"
fi

if [[ $domestic = "" ]]
then
    domestic='free';
fi
if [[ $global = "" ]]
then
    global='glb';
fi
if [[ $disconnect = "" ]]
then
    disconnect='dis';
fi
if [[ $disconnectall = "" ]]
then
    disconnectall='disall';
fi
echo "#!/bin/bash
studentID='$studentID'
password='$password'

domestic='$domestic'
global='$global'
disconnect='$disconnect'
disconnectall='$disconnectall'
# get the default encoding of system
encoding=\$(localectl status | grep \"LANG\" | cut -d '.' -f 2)
" > $filename

echo 'serverip="162.105.129.65"
serverport="5428"

range=2 # domestic -> 2 global -> 1
operation="connect" # {connect, disconnect, disconnectall}

wargs="-q -Y off -T 10 -t 3 -O - --no-check-certificate"
url="https://$serverip:$serverport/ipgatewayofpku?uid=$studentID&password=$password&range=$range&operation=$operation&timeout=1"

# args
if [ $# == 0 ]
then
    echo "Usage: $0 [command]{$domestic, $global, $disconnect, $disconnectall}"
    exit -1
fi

case $1 in
    $domestic)
        range=2
        ;;
    $global)
        range=1
        ;;
    $disconnect)
        operation="disconnect"
        ;;
    $disconnectall)
        operation="disconnectall"
        ;;
    *)
    echo "Usage: $0 [command]{$domestic, $global, $disconnect, $disconnectall}"
    exit -1;
esac

# connect to server and get the reply
status=($(wget $wargs $url | iconv -f gb2312 -t $encoding | grep "<!--IPGWCLIENT_START"))

for x in ${status[*]}
do
    if [[ "$x" =~ IPGWCLIENT ]]
    then
        echo ""
    else
        echo $x
    fi
done
' >> $filename

chmod +x ./$filename
if [ $encrypt == 1 ]
then
    gzexe ./$filename
    filename=$filename"~"
    rm ./$filename
fi
